### PR TITLE
Editted Wii footprint added fingers.

### PR DESCRIPTION
**Pull request by bwack**
Hi Tulan. I ordered boards and built and programmed. It works. I did not find the connector so I have a small pcb with edge connector. I was thinking this is something the Nunchuk64 board can have too.

My changes is to the wii connector, adding an edge connector on the same footprint as the wii connector. Let me know what you think, and if it is actually possible to mill through the plated holes like i have done.

### CODE REVIEW

**Comment by bwack** [comment]
I have ordered boards. Will have them in a week or two. Lets see how it turns out.

**Comment by djtulan** [comment]
Would be really interesting, if it is possible to cut out theses fingers....
Please inform me about the result. Maybe I merge it back then.
Since the connectors are not that expensive, I would recommend to use it.

A more expensive one is here:
https://www.raphnet-tech.com/products/wiimote_connector/index.php (faster shipping)
A cheap one is here:
https://www.aliexpress.com/item/For-WII-Right-Controller-Socket-Link-With-Left-Controller-Interface-Connector-Port/32859870700.html (longer shipping time)

**Comment by bwack** [comment]
Got reply from allpcb. Didn't approve half-plated holes without increased cost. So I removed the holes and added pads on the sides where the holes used to be. Not sure how well this will work. I'll try. Gave them new gerbers.

**Comment by djtulan** [comment]
Your Design can also cause a shortcut, if you use the connector.
see the bottom Side of the connector:
img_20180625_222456

**Comment by bwack** [comment]
Thanks. I'll just change it to an edge-connector. Anyway, I'm having fun with this adapter. Played jumpman junior last night. I love the freedom of wireless and using a joypad.

**Comment by djtulan** [comment]
Thank you anyway for your ideas. If you would like to improve something on the layout, I would suggest to change the layout, that it fits into a case. At the moment it is not well formed for any case.

**Comment by bwack** [comment]
Drew a bit more on the design today. Tried to have edge connectors next to connectors. There wasn't enough space.

Been thinking about the case. It should have a at least one screw hole somewhere perhaps in the middle. The case should have two feet such that when the button is pressed, the press goes down into the feet.

**Comment by bwack** [comment]
I'm finnished with the files. Added rounded corners for easier insertion, removed the combo connector of mine and made a pure edge connector instead (WII_CONN_EDGE) next to the one from yours (WII_CONN).

**Comment by bwack** [comment]
dsc01938
Got from allpcb today. previous design. Still waiting for the latest one with rounded corners. Connectors slides nicely onto the contacts and there is enough friction to hold them in place.

**Comment by bwack** [comment]
dsc01952

**Comment by bwack** [comment]
Soldered up this board. Something is wrong. I've got two unconnected nets. One is ground on the microcontroller and some island that is floating.. Then SCL_ and SCL is not the same on the design files and the board I have in my hand, which is very strange. Yep found it. After ordering the boards I made changes. I rotated references to tidy up and I had rotated one net by mistake. darn... Also via stitching didn't work so well either. Reload the board and my copied vias are no longer affiliated with gnd. Found that KiCad v4 has a workaround for that. https://forum.kicad.info/t/via-stitching-in-pcbnew/138/3

**Comment by bwack** [comment]
Oh dear, at some point sot23-3 has been replaced with sot23-3_handsolder it seems. Some nets are touching :-O

**Comment by bwack** [comment]
dhce9hqw4aem3wr jpg large
I wonder why this happens to me. Anyway lesson learned ! Will check DRC and make sure it has no errors before I push the last changes again !

**Comment by bwack** [comment]
Yep. Removing the short at Q4 fixed it.

**Comment by bwack** [comment]
Hi. I've decided to close this pull-request because I should have checked the effect of reversing the connector, and supply is reversed if the plug is inserted the wrong way(!) I recomend not using it. Anyway I had fun making this.

**Pull request closed without merging**
